apiVersion: v2
# When releasing, 'appVersion' is set by the Chart publishing process
appVersion: '2.26.3-branch.testing2.1177-9da4c14'
description: Speckle Server
home: 'https://speckle.systems/'
icon: 'https://app.speckle.systems/images/logo.png'
maintainers:
  - name: Speckle Systems
    url: 'https://speckle.systems/'
name: speckle-server-branch-testing2
sources:
  - 'https://github.com/specklesystems/speckle-server'
type: application
# When releasing, 'version' is set by the Chart publishing process
version: 2.26.3-branch.testing2.1177-9da4c14
