apiVersion: v2
# 'appVersion' is set by the build process to the correct value
appVersion: '2.23.17-alpha.338565'
description: Speckle Server
home: 'https://speckle.systems/'
icon: 'https://app.speckle.systems/images/logo.png'
maintainers:
  - name: Speckle Systems
    url: 'https://speckle.systems/'
name: speckle-server
sources:
  - 'https://github.com/specklesystems/speckle-server'
type: application
# 'version' is set by the build process to the correct value
version: 2.23.17-alpha.338565
