apiVersion: v2
# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.

# Set by the build process to the correct value
appVersion: '2.23.5-alpha.259596'
description: Speckle Server
home: 'https://speckle.systems/'
icon: 'https://app.speckle.systems/images/logo.png'
maintainers:
  - name: Speckle Systems
    url: 'https://speckle.systems/'
name: speckle-server
sources:
  - 'https://github.com/specklesystems/speckle-server'
type: application
# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)

# Set by the build process to the correct value
version: 2.23.5-alpha.259596
